# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790c9b2509a7f609f54cb52b18c1d334fc307ff4e10be4cf39079b0a1cf54329d96fcb3a4e7f28019191b350bdb0adf1b18c34c0d3e2e7f4983765ab1a824e4d

test:
  secret_key_base: d8b27da0b544fcc466123df918b94b2a147625289893be4cdb81c5ba43c7ef456099eded907bfe7802afb1a76cb279c9a53c319688bcc61fa93944a31a9f759f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
